# Numpy
-----
## 03. 배열 연산과 함수
### 텍스트 파일 다루기
- savetxt : 배열을 텍스트 파일로 저장
- loadtxt : 텍스트 파일을 배열로 불러오기

In [1]:
import numpy as np

data = np.random.rand(5, 3)
print(data)

# 텍스트  파일로 저장 
# np.savetxt('data.txt', data)    # 공백으로 구분
np.savetxt('data.txt', data, delimiter=",")    # ,로 구분(CSV)
# 텍스트 파일을 배열로 불러오기
# load_data = np.loadtxt('data.txt')
load_data = np.loadtxt('data.txt', delimiter=",")
print(load_data)

[[0.57882168 0.14477932 0.76304181]
 [0.23689751 0.90296899 0.17188694]
 [0.26852631 0.07945953 0.90082208]
 [0.09011038 0.81676943 0.01792437]
 [0.89786835 0.78054117 0.78568856]]
[[0.57882168 0.14477932 0.76304181]
 [0.23689751 0.90296899 0.17188694]
 [0.26852631 0.07945953 0.90082208]
 [0.09011038 0.81676943 0.01792437]
 [0.89786835 0.78054117 0.78568856]]


### 바이너리 파일 다루기
- save : 배열을 바이너리 파일로 저장
    - 넘파이 배열의 확장자는 .npy
- load : 바이너리 파일을 배열로 불러오기

※ 바이너리 형식으로 데이터를 저장하고 불러오면 데이터 손실 없이 빠르게 처리할 수 있으므로, 크기가 크고 복잡한 데이터를 다룰 때 특히 유용

In [3]:
import numpy as np
import os
# 가상의 데이터 생성
data = np.random.rand(5, 3)
print("data :\n", data)
# 데이터를 바이너리 형식으로 저장
if not os.path.exists('./generated'):
    os.makedirs('./generated')
np.save('./generated/data', data)

load_data = np.load('./generated/data.npy')
print("load_data :\n", load_data)

data :
 [[0.68993652 0.53908956 0.20540824]
 [0.09804979 0.92202796 0.78535902]
 [0.10375506 0.79131162 0.17535828]
 [0.48935349 0.29114239 0.47753649]
 [0.68199291 0.02156671 0.26660759]]
load_data :
 [[0.68993652 0.53908956 0.20540824]
 [0.09804979 0.92202796 0.78535902]
 [0.10375506 0.79131162 0.17535828]
 [0.48935349 0.29114239 0.47753649]
 [0.68199291 0.02156671 0.26660759]]
